### PR TITLE
Upgrade jwt-go library.

### PR DESCRIPTION
**Pull request by andyliuliming**

### CODE REVIEW

**Comment by emalm** [comment]
@shalako @shubhaat @aaronshurley FYI, having this PR be merged would unblock the Diego team from merging https://github.com/cloudfoundry/diego-release/pull/382 and https://github.com/cloudfoundry/diego-ssh/pull/40, since diego-release includes uaa-go-client as a submodule (I believe so that the route-emitters to communicate with the routing-api).

**Comment by shalako** [comment]
Prioritized for eng review

**Comment by andyliuliming** [comment]
this failure is because the upstream library not updated.
it's in another commit.
seems need one guy with high previlege to merge the changes  : (

**Comment by zachgersh** [comment]
this is also addressed by #12 now

**Pull request closed without merging**
